"""fresh_start

Revision ID: 509da1a49379
Revises: 
Create Date: 2026-06-29 18:16:05.238493
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '509da1a49379'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('profile_pic_url', sa.String(length=1024), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('ai_suggestions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('action_hint', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=True),
    sa.Column('data_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_suggestions_insight_type'), 'ai_suggestions', ['insight_type'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_user_id'), 'ai_suggestions', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('manufacturer', sa.String(length=60), nullable=True),
    sa.Column('serial_number', sa.String(length=60), nullable=True),
    sa.Column('bluetooth_mac', sa.String(length=20), nullable=True),
    sa.Column('firmware_version', sa.String(length=30), nullable=True),
    sa.Column('battery_level', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_paired', sa.Boolean(), nullable=False),
    sa.Column('paired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('user_goals_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('steps_achieved', sa.Integer(), nullable=True),
    sa.Column('steps_goal', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('calories_goal', sa.Integer(), nullable=False),
    sa.Column('active_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_goal_hours', sa.Float(), nullable=False),
    sa.Column('water_ml', sa.Integer(), nullable=True),
    sa.Column('water_goal_ml', sa.Integer(), nullable=False),
    sa.Column('day_score', sa.SmallInteger(), nullable=True),
    sa.Column('goal_met', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recorded_date', name='idx_goals_user_date')
    )
    op.create_index(op.f('ix_user_goals_progress_recorded_date'), 'user_goals_progress', ['recorded_date'], unique=False)
    op.create_index(op.f('ix_user_goals_progress_user_id'), 'user_goals_progress', ['user_id'], unique=False)
    op.create_table('user_health_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), sa.Computed('weight_kg / ((height_cm/100) * (height_cm/100))', persisted=True), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('fitness_goal', sa.String(length=30), nullable=True),
    sa.Column('activity_level', sa.String(length=20), nullable=True),
    sa.Column('daily_step_goal', sa.Integer(), nullable=True),
    sa.Column('daily_calorie_goal', sa.Integer(), nullable=True),
    sa.Column('daily_water_goal_ml', sa.Integer(), nullable=True),
    sa.Column('sleep_goal_hours', sa.Float(), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('resting_hr_baseline', sa.SmallInteger(), nullable=True),
    sa.Column('hrv_baseline', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_health_profiles_user_id'), 'user_health_profiles', ['user_id'], unique=True)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_is_active'), 'user_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('activity_readings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('active_minutes', sa.Integer(), nullable=True),
    sa.Column('sedentary_min', sa.Integer(), nullable=True),
    sa.Column('floors_climbed', sa.Integer(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('hourly_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', 'recorded_date', name='idx_activity_user_device_date')
    )
    op.create_index(op.f('ix_activity_readings_device_id'), 'activity_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_activity_readings_recorded_date'), 'activity_readings', ['recorded_date'], unique=False)
    op.create_index(op.f('ix_activity_readings_user_id'), 'activity_readings', ['user_id'], unique=False)
    op.create_table('heart_rate_readings',
    sa.Column('bpm', sa.SmallInteger(), nullable=False),
    sa.Column('reading_type', sa.String(length=15), nullable=False),
    sa.Column('quality_score', sa.SmallInteger(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heart_rate_readings_device_id'), 'heart_rate_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_heart_rate_readings_measured_at'), 'heart_rate_readings', ['measured_at'], unique=False)
    op.create_index(op.f('ix_heart_rate_readings_user_id'), 'heart_rate_readings', ['user_id'], unique=False)
    op.create_table('hrv_readings',
    sa.Column('rmssd_ms', sa.Float(), nullable=False),
    sa.Column('sdnn_ms', sa.Float(), nullable=True),
    sa.Column('lf_power', sa.Float(), nullable=True),
    sa.Column('hf_power', sa.Float(), nullable=True),
    sa.Column('reading_type', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hrv_readings_device_id'), 'hrv_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_hrv_readings_measured_at'), 'hrv_readings', ['measured_at'], unique=False)
    op.create_index(op.f('ix_hrv_readings_user_id'), 'hrv_readings', ['user_id'], unique=False)
    op.create_table('skin_temperature_readings',
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('baseline_c', sa.Float(), nullable=True),
    sa.Column('deviation_c', sa.Float(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skin_temperature_readings_device_id'), 'skin_temperature_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_skin_temperature_readings_measured_at'), 'skin_temperature_readings', ['measured_at'], unique=False)
    op.create_index(op.f('ix_skin_temperature_readings_user_id'), 'skin_temperature_readings', ['user_id'], unique=False)
    op.create_table('sleep_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('sleep_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sleep_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_sleep_min', sa.Integer(), nullable=False),
    sa.Column('deep_sleep_min', sa.Integer(), nullable=True),
    sa.Column('rem_sleep_min', sa.Integer(), nullable=True),
    sa.Column('light_sleep_min', sa.Integer(), nullable=True),
    sa.Column('awake_min', sa.Integer(), nullable=True),
    sa.Column('sleep_efficiency_pct', sa.Float(), nullable=True),
    sa.Column('sleep_score', sa.SmallInteger(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('avg_spo2_pct', sa.Float(), nullable=True),
    sa.Column('avg_hrv_ms', sa.Float(), nullable=True),
    sa.Column('lowest_hr', sa.SmallInteger(), nullable=True),
    sa.Column('snore_minutes', sa.Integer(), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_sessions_device_id'), 'sleep_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_sleep_sessions_user_id'), 'sleep_sessions', ['user_id'], unique=False)
    op.create_table('spo2_readings',
    sa.Column('spo2_pct', sa.Float(), nullable=False),
    sa.Column('reading_type', sa.String(length=15), nullable=False),
    sa.Column('quality_score', sa.SmallInteger(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spo2_readings_device_id'), 'spo2_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_spo2_readings_measured_at'), 'spo2_readings', ['measured_at'], unique=False)
    op.create_index(op.f('ix_spo2_readings_user_id'), 'spo2_readings', ['user_id'], unique=False)
    op.create_table('stress_readings',
    sa.Column('stress_score', sa.SmallInteger(), nullable=False),
    sa.Column('stress_label', sa.String(length=15), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_readings_device_id'), 'stress_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_stress_readings_measured_at'), 'stress_readings', ['measured_at'], unique=False)
    op.create_index(op.f('ix_stress_readings_user_id'), 'stress_readings', ['user_id'], unique=False)
    op.create_table('workouts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('workout_type', sa.String(length=30), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('min_hr', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('avg_pace', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('avg_spo2_pct', sa.Float(), nullable=True),
    sa.Column('avg_stress', sa.SmallInteger(), nullable=True),
    sa.Column('workout_score', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_device_id'), 'workouts', ['device_id'], unique=False)
    op.create_index(op.f('ix_workouts_user_id'), 'workouts', ['user_id'], unique=False)
    op.create_index(op.f('ix_workouts_workout_type'), 'workouts', ['workout_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workouts_workout_type'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_user_id'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_device_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_stress_readings_user_id'), table_name='stress_readings')
    op.drop_index(op.f('ix_stress_readings_measured_at'), table_name='stress_readings')
    op.drop_index(op.f('ix_stress_readings_device_id'), table_name='stress_readings')
    op.drop_table('stress_readings')
    op.drop_index(op.f('ix_spo2_readings_user_id'), table_name='spo2_readings')
    op.drop_index(op.f('ix_spo2_readings_measured_at'), table_name='spo2_readings')
    op.drop_index(op.f('ix_spo2_readings_device_id'), table_name='spo2_readings')
    op.drop_table('spo2_readings')
    op.drop_index(op.f('ix_sleep_sessions_user_id'), table_name='sleep_sessions')
    op.drop_index(op.f('ix_sleep_sessions_device_id'), table_name='sleep_sessions')
    op.drop_table('sleep_sessions')
    op.drop_index(op.f('ix_skin_temperature_readings_user_id'), table_name='skin_temperature_readings')
    op.drop_index(op.f('ix_skin_temperature_readings_measured_at'), table_name='skin_temperature_readings')
    op.drop_index(op.f('ix_skin_temperature_readings_device_id'), table_name='skin_temperature_readings')
    op.drop_table('skin_temperature_readings')
    op.drop_index(op.f('ix_hrv_readings_user_id'), table_name='hrv_readings')
    op.drop_index(op.f('ix_hrv_readings_measured_at'), table_name='hrv_readings')
    op.drop_index(op.f('ix_hrv_readings_device_id'), table_name='hrv_readings')
    op.drop_table('hrv_readings')
    op.drop_index(op.f('ix_heart_rate_readings_user_id'), table_name='heart_rate_readings')
    op.drop_index(op.f('ix_heart_rate_readings_measured_at'), table_name='heart_rate_readings')
    op.drop_index(op.f('ix_heart_rate_readings_device_id'), table_name='heart_rate_readings')
    op.drop_table('heart_rate_readings')
    op.drop_index(op.f('ix_activity_readings_user_id'), table_name='activity_readings')
    op.drop_index(op.f('ix_activity_readings_recorded_date'), table_name='activity_readings')
    op.drop_index(op.f('ix_activity_readings_device_id'), table_name='activity_readings')
    op.drop_table('activity_readings')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_is_active'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_health_profiles_user_id'), table_name='user_health_profiles')
    op.drop_table('user_health_profiles')
    op.drop_index(op.f('ix_user_goals_progress_user_id'), table_name='user_goals_progress')
    op.drop_index(op.f('ix_user_goals_progress_recorded_date'), table_name='user_goals_progress')
    op.drop_table('user_goals_progress')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_ai_suggestions_user_id'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_insight_type'), table_name='ai_suggestions')
    op.drop_table('ai_suggestions')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

