"""Add sleep unique constraint

Revision ID: 9f07f6f0008f
Revises: 509da1a49379
Create Date: 2026-07-01 09:00:07.518328
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9f07f6f0008f'
down_revision: Union[str, None] = '509da1a49379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_sleep_user_date', 'sleep_sessions', ['user_id', 'recorded_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_sleep_user_date', 'sleep_sessions', type_='unique')
    # ### end Alembic commands ###

