"""Add deleted_at to devices

Revision ID: cb793fdd2cfb
Revises: 9f07f6f0008f
Create Date: 2026-07-01 09:44:39.391424
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb793fdd2cfb'
down_revision: Union[str, None] = '9f07f6f0008f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'deleted_at')
    # ### end Alembic commands ###

